/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.file_sharing;

import java.awt.Color;

/**
 *
 * @author Rahul Singh
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        jButton1.setBackground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        L6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        L1.setBackground(new java.awt.Color(255, 204, 204));
        L1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L1.setText("WELCOME TO SIGN UP PAGE");
        getContentPane().add(L1);
        L1.setBounds(189, 11, 234, 26);

        L2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L2.setText("USERNAME     :");
        getContentPane().add(L2);
        L2.setBounds(84, 67, 113, 33);

        L3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L3.setText("EMAIL             :");
        getContentPane().add(L3);
        L3.setBounds(84, 132, 113, 33);

        L4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L4.setText("MOBILE NO.   :");
        getContentPane().add(L4);
        L4.setBounds(84, 201, 113, 33);

        L5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L5.setText("PASSWORD    :");
        getContentPane().add(L5);
        L5.setBounds(84, 270, 113, 33);
        getContentPane().add(T1);
        T1.setBounds(245, 69, 200, 33);
        getContentPane().add(T2);
        T2.setBounds(245, 134, 200, 33);
        getContentPane().add(T3);
        T3.setBounds(245, 203, 200, 33);
        getContentPane().add(T4);
        T4.setBounds(245, 272, 200, 33);

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 51));
        jButton1.setText("SIGN UP");
        getContentPane().add(jButton1);
        jButton1.setBounds(352, 345, 93, 33);

        jToggleButton1.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(51, 0, 51));
        jToggleButton1.setText("GO TO LOG IN PAGE");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(92, 345, 222, 33);

        L6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rahul Singh\\Downloads\\joel-henry-zc5_p_31U5g-unsplash.jpg")); // NOI18N
        getContentPane().add(L6);
        L6.setBounds(-290, -450, 940, 990);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JButton jButton1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
